### PR TITLE
`observeNewOutcomes` observation API, fix `.once` schedules

### LINKED ISSUE #56: Schedule w/ interval > 1 throws fatal exception
### Description

I am just starting to explore the Spezi framework by making a few modifications to the template application.  I tried to add a new scheduled task for the GAD-7 questionnaire with a bi-weekly interval.  I used this schedule:

let lastMonth = Calendar.current.date(byAdding: .month, value: -1, to: .today) ?? .today
schedule: .weekly(interval: 2, weekday: .saturday, hour: 8, minute: 0, startingAt: lastMonth)

I get a fatal exception that exits the app (running in a simulator).  Using interval=1 works without error.

It's difficult to trace the cause that occurs in notification while the app is first starting.  Here is the console error:

typeMismatch(SpeziScheduler.Schedule.NotificationMatchingHint, Swift.DecodingError.Context(codingPath: [], debugDescription: "Invalid number of keys found, expected one.", underlyingError: nil))

### Reproduction

Modify the template application task schedule as follows:

let lastMonth = Calendar.current.date(byAdding: .month, value: -1, to: .today) ?? .today
schedule: .weekly(interval: 2, weekday: .saturday, hour: 8, minute: 0, startingAt: lastMonth)

### Expected behavior

Fatal app exit on startup while running in simulator.

### Additional context

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### LINKED ISSUE #64: Task with `.once` schedule causes crash when querying Tasks
### Description

Defining a task that uses a `.once` schedule will result in a fatalError in SwiftData's `fetch` function.
The crash won't happen immediately when saving the task, but rather only the next time `queryTasks` is called.

### Reproduction

simply put this into an app that uses SpeziScheduler:

```swift
try! scheduler.createOrUpdateTask(
    id: "abc",
    title: "def",
    instructions: "ghi",
    schedule: .once(at: .now.addingTimeInterval(100)),
    scheduleNotifications: false
)
```

### Expected behavior

Clearly this should just work

### Additional context

fatal error output:

```
SwiftData/ModelCoders.swift:1421: Fatal error: Failed to decode a composite attribute: CompositeAttribute - name: schedule, options: [], valueType: Schedule, defaultValue: nil
      Properties:
        Attribute - name: startDate, options: [], valueType: Date, defaultValue: nil, hashModifier: nil
        CompositeAttribute - name: scheduleDuration, options: [], valueType: SwiftDataDuration, defaultValue: nil
      Properties:
        CompositeAttribute - name: duration, options: [], valueType: MappedDuration, defaultValue: nil
      Properties:
        CompositeAttribute - name: _0, options: [], valueType: MappedDuration, defaultValue: nil
      Properties:
        Attribute - name: high, options: [], valueType: Int64, defaultValue: nil, hashModifier: nil
        Attribute - name: low, options: [], valueType: UInt64, defaultValue: nil, hashModifier: nil
        Attribute - name: allDay, options: [], valueType: String, defaultValue: nil, hashModifier: nil
        Attribute - name: tillEndOfDay, options: [], valueType: String, defaultValue: nil, hashModifier: nil
        Attribute - name: recurrenceRule, options: [], valueType: Optional<Data>, defaultValue: nil, hashModifier: nil
        CompositeAttribute - name: notificationMatchingHint, options: [], valueType: Optional<NotificationMatchingHint>, defaultValue: nil
      Properties:
        CompositeAttribute - name: components, options: [], valueType: (hour: Int, minute: Int, second: Int, weekday: Optional<Int>), defaultValue: nil
      Properties:
        Attribute - name: hour, options: [], valueType: Int, defaultValue: nil, hashModifier: nil
        Attribute - name: minute, options: [], valueType: Int, defaultValue: nil, hashModifier: nil
        Attribute - name: second, options: [], valueType: Int, defaultValue: nil, hashModifier: nil
        Attribute - name: weekday, options: [], valueType: Optional<Int>, defaultValue: nil, hashModifier: nil
        CompositeAttribute - name: allDayNotification, options: [], valueType: (weekday: Optional<Int>), defaultValue: nil
      Properties:
        Attribute - name: weekday, options: [], valueType: Optional<Int>, defaultValue: nil, hashModifier: nil
{
    notificationMatchingHint =     {
    };
    scheduleDuration =     {
        tillEndOfDay =         {
        };
    };
    startDate = "2025-03-13 08:20:32 +0000";
}
typeMismatch(SpeziScheduler.Schedule.NotificationMatchingHint, Swift.DecodingError.Context(codingPath: [], debugDescription: "Invalid number of keys found, expected one.", underlyingError: nil))
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by lukaskollmer**
# `observeNewOutcomes` observation API, fix `.once` schedules

## :recycle: Current situation & Problem
This PR marks the Scheduler's `sinkDidSavePublisher(into:)` function as `@_spi(APISupport) public`, thereby allowing other Spezi packages to observe changes to the scheduler's internal ModelContext.
The specific use case here is SpeziStudy wanting to be able to run code in response to specific `Event`s getting marked as completed.
It also adds a new `@_spi(APISupport) public func observeNewOutcomes(_ handler: @MainActor @escaping (Outcome) -> Void) -> AnyObject` to the Scheduler, which allows registering a callback that will get invoked every time a new `Outome` is added to the scheduler.
Note: This API is intentionally closure-based, rather than being eg an `AsyncStream` as discussed below. The reason for this is that `Outcome` isn't sendable, but the `AsyncStream.Continuation`'s yield function operates on a `sending` parameter.

Additionally, this PR attempts to fix #56 and fix #64.

Additionally, this PR attempts to work around https://github.com/swiftlang/swift-foundation/issues/1283, which currently results in using eg `Date.now` as the start date of some `Schedule`s producing incorrect schedule occurrences.

### Alternatives considered
Instead of directly exposing the "raw" did change notification (which IMO we should still do, anwyay), we could also give the `Scheduler` directly a nice API for observing changes to it's underlying SwiftData model.
For example, we could have a function `func completions(of task: Task) -> some AsyncSequence<Outcome, Never>` that returns an `AsyncStream` which yields individual `Outcomes` for the task, as they are saved into the context.
(The immediate first issue here would bw how this should handle new Task versions getting introduced while there still are active observers on the now-outdated previous version...)
IMO we should go with the simpler change from this PR first, and then maybe add a more sophisticated API in the future, should we need to.

## :gear: Release Notes
- add `@_spi(APISupport) public func observeNewOutcomes(_ handler: @MainActor @escaping (Outcome) -> Void) -> AnyObject`
- restored the ability to use `.once` schedules (it no longer crashes)
- removed several `Duration` extensions (e.g.: `Duration.days(_:)`, `.weeks(_:)`, etc). these have been moved to [SpeziFoundation](https://github.com/StanfordSpezi/SpeziFoundation)

## :books: Documentation
is documented

## :white_check_mark: Testing
- the UITests now schedule a `.once` task; the fact that this isn't crashing the app is in itself already a regression test
- additionally, we have a View that registers a new-outcome observer with the scheduler, completes an event, and checks that the observer has been called with an outcome belonging to the just-completed event

## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]

**Comment by lukaskollmer** [comment]
@Supereg would really appreciate your input on the changes in [this commit] in particular. i'm pretty sure that this is correct, but you probably have a better understanding of the Scheduler implementation and API as a whole than i have.

**Review by PSchmiedmayer — APPROVED** [review]
Nice; thank you for the improvements and updates! 🚀

File: Sources/SpeziScheduler/Scheduler.swift [hunk 1]
```diff
@@ -677,6 +683,21 @@ extension Scheduler {
                 }
             }
     }
+    
+    /// Registers an observer function that gets called when new ``Outcome``s are created within the Scheduler.
+    ///
+    /// - parameter handler: A closure which will get invoked every time a new ``Outcome`` is added to the ``Scheduler``.
+    /// - returns: An opaque handle, to which the lifetime of the observation is tied.
+    @_spi(APISupport)
+    public func observeNewOutcomes(_ handler: @MainActor @escaping (Outcome) -> Void) -> AnyObject {
```
Comment (Supereg) [inline Sources/SpeziScheduler/Scheduler.swift:692]: I don't think returning an `AnyObject` is a great design. Especially as we loose any sort of `Sendable` guarantees, we at least would need `AnyObject & Sendable`.

However, I think a design like the following, would be way better. No need to store a reference to a closure. No need to manually spawn an unstructured task.

We could of course explore non-copyable types for this as well to get init-like functionality, but keep the value types semantics. But this would probably be a bit more restrictive at the call site.

```swift
@MainActor
public final class OutcomeSubscription: Sendable {
  private let id: UUID
  private nonisolated(unsafe) weak var scheduler: Scheduler // safe as reference counting is atomic and we do not mutate otherwise 

  init(id: UUID, scheduler: Scheduler) {
    self.id = id
    self.scheduler = scheduler
  }

  deinit {
    scheduler?.outcomeObservers.removeValue(forKey: id) // add some file private API?
  }
}
```

File: Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+        }
+        .onAppear {
+            guard observationToken == nil else {
+                return
+            }
+            observationToken = scheduler.observeNewOutcomes { outcome in
+                if outcome.task.id == "TESTTESTTEST" {
+                    didTrigger = true
+                }
+            }
```
Comment (Supereg) [inline Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift:50]: Instead of using this legacy observer based approach, couldn't we make use of structured concurrency altogether for this API and use the `.task` modifier and task cancellation to subscribe and unsubscribe? So the API surface would look like the following


```swift 
  .task {
    await scheduler.observeNewOutcomes { outcomes in
      for outcome in await outcomes {
        // do whatever you want.
      }
    }
  }
```

Of course we could make this `rethrows`. This would completely remove any of the subscription management complexity and fully embrace structured concurrency. The closure basically would get an async stream for the subscriptions and the overall subscription would be cancelled either when the task is cancelled (the view disappears) or the call returns because the subscriber is no longer interested in the subscription.

**Review by Supereg — COMMENTED** [review]
Left a few comments here and there. I think the overall approach of fixing the mentioned crash should work (TM).

File: Sources/SpeziScheduler/Scheduler.swift [hunk 3]
```diff
@@ -426,9 +431,9 @@ extension Scheduler {
     /// - Parameter taskId: The task id for which you want to delete all versions. Refer to ``Task/id``.
     public func deleteAllVersions(ofTask taskId: String) throws {
         let context = try context
-        try context.delete(model: Task.self, where: #Predicate { task in
-            task.id == taskId
-        })
+        for task in try context.fetch(FetchDescriptor(predicate: #Predicate<Task> { $0.id == taskId })) {
+            try context.delete(task)
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziScheduler/Scheduler.swift:435]: i documented this in the commit message [here](https://github.com/StanfordSpezi/SpeziScheduler/commit/47c6d51236ee0c13bb897a16b6acc56095cb8449)

File: Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift (hunk 2 above)
Comment (lukaskollmer) [reply Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift:50]: that was my initial thought as well, but using an AsyncStream doesn't work since `Outcome` isn't Sendable

Comment (Supereg) [reply Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift:50]: But AsyncSequence is generally not required to have a Sendable element, right? Couldn’t we just build our own conformance that has a MainActor isolation (or ist just non-Sendable)?

Comment (lukaskollmer) [reply Tests/UITests/TestApp/ObserveNewOutcomesTestingView.swift:50]: neither `AsyncSequence` nor `AsyncStream` constrain their `Element` type to be Sendable, but `AsyncStream.Continuation.yield(_:)` has a `sending` parameter, which doesn't work with our `Outcome` type

File: Sources/SpeziScheduler/Scheduler.swift (hunk 1 above)
Comment (lukaskollmer) [reply Sources/SpeziScheduler/Scheduler.swift:692]: we'd need to spawn the Task in either case, since global-actor-isolated classes currently still have nonisolated `deinit`s. (with the exception of course of `UIView` and `UIViewController`, where UIKit internally guarantees that they are deallocated on the main thread.)

that being said, i really like the approach of having a dedicated type; i'll change the PR accordingly

File: Sources/SpeziScheduler/Scheduler.swift (hunk 3 above)
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Sources/SpeziScheduler/Scheduler.swift:435]: update: as it turns out, `ModelContext.delete(_:)` doesn't even throw, so we don't need to worry about potential state inconsistencies here
